name: arcgis-enterprise-image-builder

services:
  arcgis-base:
    image: "arcgis-base:${BUILD_TAG}"
    build:
      context: .
      dockerfile: ./base/Dockerfile
      args:
        - BUILD_MODE=${BUILD_MODE}
        - UBUNTU_VERSION_TAG=${UBUNTU_VERSION_TAG}

  arcgis-server:
    image: "arcgis-server:${BUILD_TAG}"
    build:
      context: .
      dockerfile: ./arcgis-server/Dockerfile
      args:
        - BUILD_TAG=${BUILD_TAG}
        - ARCGIS_PATCH_STRATEGY=${ARCGIS_PATCH_STRATEGY}
        - ARCHIVE_DIR=${ARCHIVE_DIR}
        - SERVER_ARCHIVE_FILE=${SERVER_ARCHIVE_FILE}
    depends_on:
      - arcgis-base

  geoevent-server:
    image: "geoevent-server:${BUILD_TAG}"
    build:
      context: .
      dockerfile: ./geoevent-server/Dockerfile
      args:
        - BUILD_TAG=${BUILD_TAG}
        - ARCGIS_PATCH_STRATEGY=${ARCGIS_PATCH_STRATEGY}
        - ARCHIVE_DIR=${ARCHIVE_DIR}
        - GEOEVENT_ARCHIVE_FILE=${GEOEVENT_ARCHIVE_FILE}
    depends_on:
      - arcgis-server

  arcgis-datastore:
    image: "arcgis-datastore:${BUILD_TAG}"
    build:
      context: .
      dockerfile: ./datastore/Dockerfile
      args:
        - BUILD_TAG=${BUILD_TAG}
        - ARCGIS_PATCH_STRATEGY=${ARCGIS_PATCH_STRATEGY}
        - ARCHIVE_DIR=${ARCHIVE_DIR}
        - DATASTORE_ARCHIVE_FILE=${DATASTORE_ARCHIVE_FILE}
    depends_on:
      - arcgis-base

  portal:
    image: "arcgis-portal:${BUILD_TAG}"
    build:
      context: .
      dockerfile: ./portal/Dockerfile
      args:
        - BUILD_TAG=${BUILD_TAG}
        - ARCGIS_PATCH_STRATEGY=${ARCGIS_PATCH_STRATEGY}
        - ARCHIVE_DIR=${ARCHIVE_DIR}
        - PORTAL_ARCHIVE_FILE=${PORTAL_ARCHIVE_FILE}
    depends_on:
      - arcgis-base

  proxy:
    image: "proxy-server:${BUILD_TAG}"
    build:
      context: .
      dockerfile: ./proxy-server/Dockerfile
      args:
        - BUILD_TAG=${BUILD_TAG}
